### ISSUE TITLE
CameraX

### ISSUE THREAD

**Issue by mag0716** [mag0716/Google_IO_2019_CatchUp#1]
## TODO

- [x] セッションみる
- [x] [リファレンス](https://developer.android.com/training/camerax/architecture) 読む
- [x] [Codelabs](https://codelabs.developers.google.com/codelabs/camerax-getting-started/index.html?index=..%2F..index#0) やる
- [x] [サンプル](https://github.com/android/camera) 軽く見る
